### PR TITLE
Django branch

### PR DESCRIPTION
**Pull request by Ahmed-cmd-web**
## This branch is for all future Django commits.

### CODE REVIEW

**Comment by OmarElsebaey001** [comment]
Kindly remove the pipfiles, and provide a requirements.txt file 
expectation: pip install -r requirements.txt

**Comment by OmarElsebaey001** [comment]
in the summary url : models/models/<id>/summary, we will need to fetch the latest version of the model

**Comment by OmarElsebaey001** [comment]
Good job adding the dbMocker script,
another note is to populate it with the necessary fields: models, portfolios,versions and so on , not only models

**Comment by Ahmed-cmd-web** [comment]
Maybe enhance the DBmocker later

**Comment by Ahmed-cmd-web** [comment]
> in the summary url : models/models//summary, we will need to fetch the latest version of the model

I need more details if possible

**Pull request merged**
